
import { lazy } from "react";
import "./globals.css";
const Main = lazy(() => import("./main"));

export const metadata = {
  title: "Create Next App",
  deScription: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Main >{children}</Main>
  );
}
