
import { Header } from "@/component/admin/particals/Header";
import "../globals.css";
import { Sidebar } from "@/component/admin/particals/Sidebar";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { unstable_noStore } from "next/cache";
export default function RootLayout({ children }) {
  unstable_noStore();
  return (
    <html lang="en">

      <body>
        <div className="flex min-h-screen bg-gray-100">
          {/* Sidebar */}
          <Sidebar />

          <div className="flex-1 flex flex-col ">
            <Header />
            <main className="flex-1 p-6  ">
              <div className="bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            {children}
            </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  )
}
