export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import "../globals.css";
export default function LoginLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
